// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
dart;
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPmkKwjF_pnlV43-nK3PDVcNdLyr58axs',
    appId: '1:839651545510:web:3735c25b1f3ba0b29fbf67',
    messagingSenderId: '839651545510',
    projectId: 'wtmanagement-b4597',
    authDomain: 'wtmanagement-b4597.firebaseapp.com',
    storageBucket: 'wtmanagement-b4597.firebasestorage.app',
    measurementId: 'G-FCCMJZCMEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBCsUkVZhEO5NGDpecCkzy9wk4wlokfA',
    appId: '1:839651545510:android:cf0097e673e5bde39fbf67',
    messagingSenderId: '839651545510',
    projectId: 'wtmanagement-b4597',
    storageBucket: 'wtmanagement-b4597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgpTKnXIlyWfCkLcF2Fh3Z8IcqxVJQpY',
    appId: '1:839651545510:ios:349958b5d36d11ad9fbf67',
    messagingSenderId: '839651545510',
    projectId: 'wtmanagement-b4597',
    storageBucket: 'wtmanagement-b4597.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgpTKnXIlyWfCkLcF2Fh3Z8IcqxVJQpY',
    appId: '1:839651545510:ios:349958b5d36d11ad9fbf67',
    messagingSenderId: '839651545510',
    projectId: 'wtmanagement-b4597',
    storageBucket: 'wtmanagement-b4597.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPmkKwjF_pnlV43-nK3PDVcNdLyr58axs',
    appId: '1:839651545510:web:4e68a92a7246d6f39fbf67',
    messagingSenderId: '839651545510',
    projectId: 'wtmanagement-b4597',
    authDomain: 'wtmanagement-b4597.firebaseapp.com',
    storageBucket: 'wtmanagement-b4597.firebasestorage.app',
    measurementId: 'G-56PRVM045J',
  );
}
